### PR TITLE
Fixes overlapping timeslot bug

### LINKED ISSUE #94: overlapping timeslot bug
to replicate:
1. create a booking with `start = 7pm` and `end = 9pm`
2. create another booking of the same room and date with `start = 8pm` and `end = 10pm`

observed behaviour:
2nd booking is created successfully

intended behaviour:
booking should be validated as false
app should block user from creating such a booking

### PR DESCRIPTION
**Pull request by welvin21**
Closes #94

### CODE REVIEW

File: src/functions/validateTime.js [hunk 1]
```diff
@@ -30,10 +54,12 @@ export const validateTime = (bookings, date, start, end) => {
     alert("You can't book more than 60 days in advance.");
     return false;
   } else {
-    for (let i = 0; i < bookings.length; ++i) {
+    const dissectedBookings = dissectBookings([...bookings]);
```
Comment (98sean98) [inline src/functions/validateTime.js:49]: `[...bookings]` ? just do `dissectBookings(bookings)` cuz `bookings` is an array right?

Comment (welvin21) [reply src/functions/validateTime.js:49]: Oh yaa, I did that on purpose actually. Since array is passed by reference as a function argument, `[...bookings]` creates a new copy of `bookings` and won't effect the original `bookings` array. Just to be safe, in case there is any data changing operation in `dissectBookings` tbh 😂

File: src/functions/validateTime.js [hunk 2]
```diff
@@ -30,10 +54,12 @@ export const validateTime = (bookings, date, start, end) => {
...
+
+    for (let i = 0; i < dissectedBookings.length; ++i) {
       if (
-        moment(bookings[i].start).isSame(startTime, 'hour') ||
-        moment(bookings[i].end).isSame(endTime, 'hour')
+        moment(dissectedBookings[i].startTime).isSame(startTime, 'hour') ||
+        moment(dissectedBookings[i].endTime).isSame(endTime, 'hour')
```
Comment (98sean98) [inline src/functions/validateTime.js]: algorithm seems a bit wrong

when `startTime` is `8am` and `endTime` is `12pm`, and there's an existing booking with `9am` to `11am`, 
```
moment(dissectedBookings[i].startTime).isSame(startTime, 'hour') ||
  moment(bookings[i].end).isSame(endTime, 'hour')
```
seems to always be false, which results in booking being valid when it actually isn't.

Comment (welvin21) [reply src/functions/validateTime.js]: > algorithm seems a bit wrong
> 
> when `startTime` is `8am` and `endTime` is `12pm`, and there's an existing booking with `9am` to `11am`,
> 
> ```
> moment(dissectedBookings[i].startTime).isSame(startTime, 'hour') ||
>   moment(bookings[i].end).isSame(endTime, 'hour')
> ```
> 
> seems to always be false, which results in booking being valid when it actually isn't.

Ohh I see, I kept in mind that max number of hours is 2 when doing that. Will commit a change soon, thanks for the heads up!

File: src/functions/validateTime.js [hunk 3]
```diff
@@ -1,5 +1,29 @@
...
+    let { start, end } = booking;
+    start = moment(start);
+    end = moment(end);
+
+    for (let i = start; i.isBefore(end); i = i.add(1, 'hours')) {
+      const startTime = moment(i);
+      const endTime = moment(i).add(1, 'hours');
+      dissectedBookings.push({
+        startTime,
+        endTime
```
Comment (98sean98) [inline src/functions/validateTime.js]: should remove the `endTime` field since its not used anymore

File: src/functions/validateTime.js [hunk 4]
```diff
@@ -34,7 +26,7 @@ export const validateTime = (bookings, date, start, end) => {
   const duration = moment.duration(endTime.diff(startTime));
   const hours = duration.asHours();
   const dateChosen = moment(date).startOf('date');
-  if (hours > 2) {
+  if (hours > 12) {
     alert('Maximum hours of booking per person is 2 hours.');
```
Comment (98sean98) [inline src/functions/validateTime.js]: is the maximum confirmed to be 12? if so, the error message should correspond to that too

Comment (welvin21) [reply src/functions/validateTime.js]: ohh no, i did that for development purpose but forgot to change that back to 2 😂

**Review by 98sean98 — APPROVED** [review]
